version: '3.8'

services:
  chatbot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"  # If we add a web interface later
    command: python src/chatbot.py 