version: '3.8'

services:
  chatbot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"  # If we add a web interface later
    stdin_open: true  # Enable interactive input
    tty: true        # Enable TTY
    command: python -u src/chatbot.py  # -u flag for unbuffered output 